'use client'

import Head from "next/head";
import Image from "next/image";

import layout from "@/styles/layout.module.css";
import firstview from "@/styles/firstview.module.css";
import styles from "@/styles/company.module.css";
import heading from "@/styles/heading.module.css";
import table from "@/styles/table.module.css";

import Header from "../components/header";
import Footer from "../components/footer";
import Contact from "../components/contactForm";
// import heading from "@/styles/heading.module.css";


//要素が交差したときクラス付与
function callback(entries: any) {
  entries.forEach((entry: any) => {
    const target = entry.target;
    if (entry.isIntersecting) {
      target.classList.add('-active');
    }
  });
}



export default function Company() {

  if (typeof document !== 'undefined') {

    const target = document.querySelectorAll('.js-scrollEffect');

    //オプション設定
    const options = {
      root: null,
      rootMargin: '-10% 0px',
      threshold: 0,
    };

    //Intersection Observerの呼び出し
    const observer = new IntersectionObserver(callback, options);
    target.forEach((tgt) => {
      observer.observe(tgt);
    });
  }


  return (
    <>
      <Head>
        <title>井手設備 / 企業情報</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>




      <Header />

      <main>
        <div className={firstview.backImage}>
          <img src="/recruitment.jpg" alt="recruitment" />
          <div className={`${firstview.inner} ${layout.contents}`}>
            <p className={`${firstview.subttl} fadeIn -active`}>COMPANY</p>
            <h2 className={`${firstview.ttl} fadeIn -active`}>企業情報</h2>
            <p className={`${firstview.text} fadeIn -active`}>井手設備は堅実な技術で確かな安心をご提供する給排水工事のプロです。</p>
          </div>
        </div>


        <section className={`${styles.message}`}>
          <div className={`${layout.contents} ${layout.topMargin} ${layout.flex}`}>
            <div className={`${layout.contentsWrap}`}>
              <div className={heading.inner}>
                <p className={`${heading.subttl} reveal-text js-scrollEffect`}>MESSAGE</p><br></br>
                <h2 className={`${heading.ttl} reveal-text js-scrollEffect`}>メッセージ</h2>
                <p className={`${heading.text} reveal-text js-scrollEffect`}>専門的な技術と豊富な経験<br></br>最適な施工技術で業務を遂行</p>
              </div>
            </div>
            <div className={`${layout.contentsWrap}`}>
              <p className={`${layout.contentsText} fadeIn js-scrollEffect`}>私たちの最優先事項は、法令順守と品質の確保です。<br></br>厳格な規制に則りながら、高品質な材料と最新の技術を活用し安全かつ信頼性の高い設備を提供しています。お客様の安心と安全を第一に考え、常に最善の結果を追求してまいります。<br></br><br></br>井手設備は長年の実績と高い専門性を持ちながら、お客様の信頼を築き上げてまいりました。これからもお客様のニーズに応え、より良いサービスを提供するために努力し続けます。</p>
            </div>
          </div>
        </section>

        <section className={`${styles.policy}`}>
          <div className={styles.head}>
            <p className={`${heading.centerSubttl} fadeIn js-scrollEffect`}>POLICY</p>
            <h2 className={`${heading.centerTtl} fadeIn js-scrollEffect`}>井手設備の方針</h2>
          </div>
          <div className={styles.policyList}>
            <ul>
              <li className="fadeIn js-scrollEffect">
                <div className={styles.num}>01</div>
                <div className={styles.data}>
                  <h3>規制や法令の遵守</h3>
                  <p>地域の建築基準や建築規制、衛生規則などの法令や規制を尊重し適切な許認可を取得、施工に関する法的な義務を遵守します。</p>
                </div>
              </li>
              <li className="fadeIn js-scrollEffect">
                <div className={styles.num}>02</div>
                <div className={styles.data}>
                  <h3>品質と耐久性</h3>
                  <p>使用する材料や施工技術は、品質と耐久性に優れている必要があります。高品質な配管材料や部品を選択し、適切な施工方法を採用することで、長期間安定した機能性を確保します。</p>
                </div>
              </li>
              <li className="fadeIn js-scrollEffect">
                <div className={styles.num}>03</div>
                <div className={styles.data}>
                  <h3>施工技術と経験</h3>
                  <p>給排水設備工事は専門的な技術と経験が必要な作業です。<br></br>資格を持つ専門家や経験豊富な施工業者を選択し適切な施工技術を確保します。</p>
                </div>
              </li>
              <li className="fadeIn js-scrollEffect">
                <div className={styles.num}>04</div>
                <div className={styles.data}>
                  <h3>安全対策</h3>
                  <p>安全対策を適切に実施し、作業現場での事故や怪我のリスクを最小限に抑えます。安全な作業環境を確保するための適切な装備や手順を用意し、作業員の安全を確保します。</p>
                </div>
              </li>
              <li className="fadeIn js-scrollEffect">
                <div className={styles.num}>05</div>
                <div className={styles.data}>
                  <h3>コミュニケーションと調整</h3>
                  <p>施工に関わるすべての関係者との適切なコミュニケーションを確保し、プロジェクトの進行状況や変更点などを適切に調整します。<br></br>関係者との密な連携を図り、円滑な施工プロセスを実現します。</p>
                </div>
              </li>
            </ul>
          </div>
        </section>

        <section className={`${styles.summary}`}>
          <div className={styles.head}>
            <p className={`${heading.centerSubttl} fadeIn js-scrollEffect`}>SUMMARY</p>
            <h2 className={`${heading.centerTtl} fadeIn js-scrollEffect`}>会社概要</h2>
          </div>
          <div className={`${table.tableWrap} fadeIn js-scrollEffect`}>
            <table>
              <tbody>
                <tr>
                  <th>社名</th>
                  <td>井手設備</td>
                </tr>
                <tr>
                  <th>設立</th>
                  <td>情報未設定</td>
                </tr>
                <tr>
                  <th>資本金</th>
                  <td>情報未設定</td>
                </tr>
                <tr>
                  <th>代表取締役</th>
                  <td>井手 昌輔</td>
                </tr>
                <tr>
                  <th>従業員数</th>
                  <td>3名</td>
                </tr>
                <tr>
                  <th>所在地</th>
                  <td>大阪府大東市寺川5丁目</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>


        <Contact />
      </main>

      <Footer />
    </>
  );
}
